version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      go-deps:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3

  - package-ecosystem: 'npm'
    directory: '/dashboard'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      dashboard-deps:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/internal/e2e'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    groups:
      e2e-deps:
        patterns:
          - '*'
